### ISSUE TITLE
Parser Output is empty

### ISSUE THREAD

**Issue by dirflash** [sttrayno/ASA-Telemetry-Guide#2]
When I run asascript.py, it looks like genie is complaining about running 'show vpn-sessiondb'.

(env3) root@e8ccbefafdbe:/opt/telegraf# /opt/telegraf/env3/bin/python /opt/telegraf/ASA-Telemetry-Guide/telegraf/scripts/asascript.py
Traceback (most recent call last):
  File "/opt/telegraf/ASA-Telemetry-Guide/telegraf/scripts/asascript.py", line 11, in <module>
    p1 = dev.parse('show vpn-sessiondb')
  File "src/genie/conf/base/device.py", line 551, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 578, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 290, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 285, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 222, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaEmptyParserError: Parser Output is empty

When I run it through pyats shell, it doesn't seem to have a problem:

`(env3) root@e8ccbefafdbe:/opt/telegraf# pyats shell --testbed-file /opt/telegraf/ASA-Telemetry-Guide/telegraf/scripts/testbed-asa.yaml
 testbed
 testbed.devices
 device = testbed.devices['ASAv']
 device.connect()
 device.execute('show vpn-sessiondb')

2020-11-17 19:00:28,513: %UNICON-INFO: +++ ASAv: executing command 'show vpn-sessiondb' +++
show vpn-sessiondb

 No sessions to display.

ASAv#`

Any clue as to why this is happening?

**Comment by sttrayno** [comment]
Hi there, seems like theres no VPN sessions on the ASA you're using which is why the parsers failing. That error would be expected in that case. I can change the code to handle the exception, give me a few days.
